// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
export enum StoreNames {
    VisualizationStore = 'VisualizationStore',
    TabStore = 'TabStore',
    VisualizationScanResultStore = 'VisualizationScanResultStore',
    CommandStore = 'CommandStore',
    FeatureFlagStore = 'FeatureFlagStore',
    LaunchPanelStateStore = 'LaunchPanelStateStore',
    DevToolsStore = 'DevToolsStore',
    DetailsViewStore = 'DetailsViewStore',
    AssessmentStore = 'AssessmentStore',
    ScopingPanelStateStore = 'ScopingPanelStateStore',
    InspectStore = 'InspectStore',
    UserConfigurationStore = 'UserConfigurationStore',
    PathSnippetStore = 'PathSnippetStore',
    UnifiedScanResultStore = 'UnifiedScanResultStore',
    CardSelectionStore = 'CardSelectionStore',
    DeviceStore = 'DeviceStore',
    WindowStateStore = 'WindowStateStore',
    ScanStore = 'ScanStore',
    PermissionsStateStore = 'PermissionsStateStore',
    DebugToolsNavStore = 'DebugToolsNavStore',
    AndroidSetupStore = 'AndroidSetupStore',
}
